### ISSUE TITLE
Poi not building vue project, throwing required loader error

### ISSUE THREAD

**Issue by hitautodestruct** [poi-bundler/website#4]
When running the simple `poi` command on a vuejs project everything works as expected.

When running the `poi build` command I keep getting this error for all of my inline scss code:
`You may need an appropriate loader to handle this file type.`

I have `lang="scss"` on all my `<style>` tags and have I have installed `node-sass` and `sass-loader` as per the docs.

But I keep getting an error. See below:

<img width="444" alt="image" src="https://user-images.githubusercontent.com/687730/39244483-7006354c-4899-11e8-8736-9d5ff950caa7.png">

**Comment by egoist** [comment]
hmm are you using vue-loader 15?

**Comment by hitautodestruct** [comment]
I installed vue-loader in the project and yes it is version 15. Still getting the same result.

**Comment by egoist** [comment]
Just tried and it works well, a minimal repo would help

**Comment by hitautodestruct** [comment]
I had poi installed both globally and locally.
I just uninstalled poi from the global npm (npm un -g poi) and I am now getting a different error:
`Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'sassLoader' of undefined`

**Comment by hitautodestruct** [comment]
> Just tried and it works well, a minimal repo would help
Good point, I will try and set up a skeleton project.

**Comment by hitautodestruct** [comment]
OK! It's working!

I had multiple modules installed which somehow confused poi.
I uninstalled: `css-loader` `file-loader` `postcss-loader` `vue-template-compiler`

Hopes this helps someone.
@egoist Maybe you should add some kind of warning to the docs or check out why that happends?

Thanks for this great tool !! And your fantastic help!
